// Copies the Codify design tokens into plain CSS for pages without Tailwind.
// Source of truth: ../codify-app-web/design/tokens.css (do not edit the copy).
// Run: node scripts/design-tokens.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../../codify-app-web/design/tokens.css');
const out = resolve(here, '../src/tokens.css');

const lines = readFileSync(src, 'utf8').split('\n');
const result = [];
for (const line of lines) {
  if (/^\s*--[a-z-]+\*:\s*initial;/.test(line)) continue; // Tailwind namespace resets
  if (/^\s*@utility\b/.test(line)) continue; // Tailwind utilities: use var(--progress) directly
  result.push(line.replace(/^@theme \{/, ':root {'));
}
const header =
  '/* GENERATED by scripts/design-tokens.mjs from codify-app-web/design/tokens.css. Do not edit; edit the source and rerun. */\n';
writeFileSync(out, header + result.join('\n'));
console.log(`tokens written: ${out}`);
